config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "pages#home"
  get "historical", to: "pages#historical"
  get "profil", to: "pages#profil"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :prescriptions do
    resources :follow_ups, only: %i[index show new create edit update]
    resources :measures, only: %i[show new create] do
      resources :measurements, only: %i[new create edit update]
    end
  end
  resources :follow_ups, only: %i[edit update destroy]
  resources :measures, only: %i[index show edit update destroy]

  resources :pathologies, only: %i[index show edit update new create]
  resources :appointments
  get "day_calendar/:date_str", to: "appointments#day_calendar", as: :day_calendar
  # get "dashboard", to: "pages#dashboard"
end

app/models/prescription.rb
class Prescription < ApplicationRecord
  belongs_to :user
  has_many :patho_prescriptions, dependent: :destroy
  has_many :follow_ups
  has_many :measures

  validates :title, presence: true, length: { minimum: 6 }
  validates :description, presence: true, length: { maximum: 500 }
  # validates :start_date, presence: true
  # validates :end_date, presence: true

  def start_time
    self.end_date
  end
end

app/controllers/prescriptions_controller.rb
class PrescriptionsController < ApplicationController
before_action :set_prescription, only: [:show, :edit, :update, :destroy]

  def index
    @prescriptions = Prescription.where(user_id: current_user)
  end

  def show; end

  def new
    @prescription = Prescription.new
  end

  def create
    @prescription = Prescription.new(prescription_params)
    @prescription.user = current_user
    if @prescription.save!
      redirect_to prescription_path(@prescription)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    @prescription.update!(prescription_params)
      redirect_to prescription_path
  end

  # def destroy
  #   @prescription.destroy
  #    redirect_to prescription_path, status: :see_others
  # end

  private

  def prescription_params
    params.require(:prescription).permit(:title, :description, :start_date, :end_date, :practician, :user_id)
  end

  def set_prescription
    @prescription = Prescription.find(params[:id])
  end
end

app/views/prescriptions/edit.html.erb
<div class="header">
  <div class= "header-title">
  <% if user_signed_in? %>
    <h1>Modifier votre ordonnance</h1>
    <% end %>
  </div>
</div>
<h1 class="edit-form"></h1>
<div class="container form">
      <%= simple_form_for @prescription, data: { controller: 'flatpickr' } do |f| %>

      <div>
        <%= f.input :title, placeholder: 'Titre', label: "Titre" %>
        <%= f.input :description, placeholder: 'Description'%>
      </div>

        <div>
          <%= f.input :start_date, as: :string, input_html: { data: { flatpickr_target: "startTime" } }, label: "Commence le" %>
          <%= f.input :end_date, as: :string, input_html: { data: { flatpickr_target: "endTime" }, id: 'end_time' }, label: "Fini le" %>
        </div>

        <div>
          <%= f.input :practician, placeholder: 'The name of the practician', label: "Praticien"%>
        </div>
        <%= f.submit 'modifier',class: "bouton edit-style" %>

  <% end %>
</div>

app/views/prescriptions/index.html.erb
<div class="header">
  <div class= "header-title">
  <% if user_signed_in? %>
    <h1>Mes prescriptions</h1>
    <% end %>
  </div>
</div>
<div class = "container mt-1">
  <div class="medical-file bg-transparent d-flex justify-content-center m-2">
      <div class= "plus">
        <p><%= link_to '+', new_prescription_path, class: ""%></p>
      </div>
  </div>
  <ul class = "list-group" style = "padding-left: 0px">
    <% @prescriptions.each do |prescription| %>
      <% if (Date.today <= prescription.end_date && prescription.start_date <= Date.today) %>
        <%= link_to(prescription_path(prescription)) do %>
          <div class = "m-1 bouton d-flex justify-content-center">
            <p><%= prescription.title %></p>
          </div>
        <% end %>
      <% else %>
        <%# <div>
        <p class = "card-title h2"> Vous n'avez pas de prescription </p>
        </div> %>
      <% end %>
    <% end %>
  </ul>
</div>


<%# <div class = "container">
  <h1 class = "">Vos prescriptions</h1>
  <ul class = "card-product">
    <% @prescriptions.each do |prescription| %>
      <%# <% if (Date.today <= prescription.end_date && prescription.start_date <= Date.today) %>
        <%# <div class = "card-title h2"> %>
        <%# <%= link_to prescription.title, prescription_path(prescription) %>
        <%# </div> %>
        <%# <div class = "card-description" p> %>
        <%# <ul>Description:<%= prescription.description %>
        <%# <ul>Expiration:<%= prescription.end_date %>
        <%# </div> %>
        <%# <% else %>
        <%# <div>
        <p class = "card-title h2"> Vous n'avez pas de prescription </p>
        </div> %>
      <%# <% end %>
    <%# <% end %>
  <%# </ul> %>
    <%# <p><%= link_to 'Créer une prescription', new_prescription_path, class: "bouton" %>
<%# </div> %>

app/views/prescriptions/new.html.erb
<div class="header">
  <div class= "header-title">
    <% if user_signed_in? %>
      <h1>Créer une Ordonnance</h1>
    <% end %>
  </div>
</div>

<div class="edit-form">
  <div class="container form">
    <div class="bg-white rounded p-3 shadow">
      <%= simple_form_for @prescription, data: { controller: 'flatpickr' } do |f| %>
        <div>
          <%= f.input :title, placeholder: 'Ordonnance Cardio - pré-operation', label: "Titre", class: "black-label"%>
          <%= f.input :description, placeholder: "Mise en place d'un traitement avant l'opération"%>
        </div>

        <div>
          <%= f.input :start_date, label: "Commence le", as: :string, input_html: { data: { flatpickr_target: "startTime" } },value: "Commence le" %>
          <%= f.input :end_date, label: "Fini le", as: :string, input_html: { data: { flatpickr_target: "endTime" }, id: 'end_time' },value: "Fini le" %>
        </div>

        <div>
          <%= f.input :practician, placeholder: 'Dr.HOUSE',label: "Praticien"%>
          <%= f.submit 'Créer', class: "bouton edit-style" %>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/prescriptions/show.html.erb
<div class="header">
  <div class= "header-title">
  <% if user_signed_in? %>
    <h1>Ordonnance</h1>
    <% end %>
  </div>
</div>
<div class="container">
  <div class="my-2 ">
    <div class = "d-flex justify-content-between">
      <h1 class =""><strong><%= @prescription.title %></strong> </h1>
      <%= link_to(edit_prescription_path(@prescription)) do %>
        <p class= "mt-1">✏️</p>
      <% end %>
    </div>

    <div class="measures__values-2 row">
      <h4><%= @prescription.practician %></h4>
      <p><%= @prescription.description %></p>
      <p> Debut : <strong><%= @prescription.start_date %></strong> - Fin : <strong><%= @prescription.end_date %></strong></p>
      <p>Rappel de renouvellement : <%= @prescription.end_date-5 %></p>
    </div>
  </div>

  <div class="m-3 d-flex align-items-center justify-content-between">
    <h2 class = "my-1">Mes traitements </h2>
    <p class = "plus"><%= link_to "+", new_prescription_follow_up_path(@prescription) %></p>
  </div>

  <div>
    <ul class = "list-group">
      <% @prescription.follow_ups.each do |f| %>
        <%= link_to(prescription_follow_up_path(@prescription,f)) do %>
          <li class = "m-1 bouton d-flex justify-content-center"><%= f.title %></li>
        <% end %>
      <% end %>
    </ul>
  </div>

  <div class = "m-3 d-flex align-items-center justify-content-between">
    <h2 class = "my-1">Mes mesures </h2>
    <p class = "plus"><%= link_to "+", new_prescription_measure_path(@prescription) %></p>
  </div>
  <div>
    <ul class = "list-group">
      <% @prescription.measures.each do |m| %>

<%= link_to(prescription_measure_path(@prescription,m)) do %>
        <li class = "m-1 bouton d-flex justify-content-center"><%=m.title%></li>
<% end %>


      <% end %>
    </ul>
  </div>
</div>
<p class ="mt-3">.</p>