config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "pages#home"
  get "historical", to: "pages#historical"
  get "profil", to: "pages#profil"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :prescriptions do
    resources :follow_ups, only: %i[index show new create edit update]
    resources :measures, only: %i[show new create] do
      resources :measurements, only: %i[new create edit update]
    end
  end
  resources :follow_ups, only: %i[edit update destroy]
  resources :measures, only: %i[index show edit update destroy]

  resources :pathologies, only: %i[index show edit update new create]
  resources :appointments
  get "day_calendar/:date_str", to: "appointments#day_calendar", as: :day_calendar
  # get "dashboard", to: "pages#dashboard"
end

app/views/pages/historical.html.erb
<div class="header">
  <div class= "header-title">
  <% if user_signed_in? %>
    <h1>Mon historique</h1>
    <% end %>
  </div>
</div>
<div class = "container">
  <h1 class = "mt-2"><strong>Mes ordonnances passées</strong></h1>
  <ul class = "list-group">
    <% @prescriptions.each do |prescription| %>
        <% if prescription.end_date < Time.now %>
          <li class = "">
            <p><%= link_to prescription.title, prescription_path(prescription), style:"text-decoration:none", class:"m-1 bouton d-flex justify-content-center" %></p>
            <p class ="ms-3">Terminée le <%= prescription.start_date %></p>
            <p class ="ms-3">Precrit par : <%= prescription.practician %></p>
          </li>
        <% end %>
    <% end %>
  </ul>



  <h1 class = "mt-2"><strong>Mes traitements passés</strong></h1>
    <ul class = "list-group">
      <% @prescriptions.each do |prescription| %>
        <% prescription.follow_ups.each do |followup| %>
          <% if followup.end_date < Time.now %>
            <li class = "">
              <p><%= link_to followup.title, prescription_follow_up_path(prescription, followup), style:"text-decoration:none", class:"m-1 bouton d-flex justify-content-center" %></p>
              <p class ="ms-3">Terminée le <%= followup.start_date %></p>
              <p class ="ms-3">Precrit par : <%= prescription.practician %></p>
            </li>
          <% end %>
        <% end %>
      <% end %>
    </ul>

</div>

app/views/pages/home.html.erb
<div class="header">
  <div class= "header-title">
  <% if user_signed_in? %>
    <h1>Bonjour <%= current_user.first_name%></h1>
    <% end %>
  </div>
</div>
<div class="container">
    <h5 class="couleur mt-3">HealthConnect</h5>
  <% if user_signed_in? %>

    <div class="medical-file justify-content-center rounded bg-transparent">
      <div class="mb-2 col-12 col-lg-6 rounded">
        <h2 class = "mb-2"> Vous avez un rendez-vous 🛎️</h2>
          <ul class = "list-group">
            <li class = " m-1 bouton d-flex justify-content-center">
              <p>RDV - Dr.HOUSE</p>
            </li>
          </ul>
      </div>


      <div class="mb-2 col-12 col-lg-6 rounded">
        <h2 class = "mt-4"> Mesures du jour 📈</h2>
          <ul class = "list-group">
            <% @prescriptions.each do |prescription| %>
              <% prescription.measures.each do |measure| %>
                <%= link_to(prescription_measure_path(prescription, measure)) do %>
                  <% if ((Time.now < measure.end_date && measure.start_date < Time.now)) %>
                    <li class = " m-1 bouton d-flex justify-content-center">
                      <p><%= measure.title %></p>
                    </li>
                  <% end %>
                <% end %>
              <% end %>
            <% end %>
          </ul>
      </div>
      <div class="mb-2 col-12 col-lg-6 rounded">
        <h2 class = "mt-4">Traitements du jour 💊</h2>
          <ul class = "list-group">
            <% @prescriptions.each do |prescription| %>
              <% prescription.follow_ups.each do |followup| %>
                <%= link_to(prescription_follow_up_path(prescription, followup)) do %>
                  <% if ((Time.now < followup.end_date && followup.start_date < Time.now)) %>
                    <li class = "m-1 bouton d-flex justify-content-center">
                      <p> <%= followup.title %></p>
                    </li>
                  <% end %>
                <% end %>
              <% end %>
            <% end %>
          </ul>
      </div>
    </div>

  <% else %>
  <div class = "mt-6 container d-flex justify-content-center">
    <%= link_to "Se connecter", new_user_session_path, class: 'mt-5 bouton' %>
  </div>
  <% end %>
</div>

<p class ="mt-2"> </p>

app/views/pages/profil.html.erb
<div class="header">
  <div class= "header-title">
  <% if user_signed_in? %>
    <h1>Mon profil</h1>
    <% end %>
  </div>
</div>
<div class = "container">
  <h1 class ="mt-2">Données personnelles </h1>
  <p>Prénom : <%= @user.first_name %></p>
  <p>Nom : <%= @user.last_name %></p>
  <p>Age : 38 ans</p>
  <p>Sexe : Femme </p>
  <p>Adresse : 1 rue de la paix, 75000 Paris</p>
  <p>Numéro de téléphone : 06 12 34 56 78</p>
  <p>Adresse mail : <%= @user.email %></p>

  <h1 class ="mt-2">Données administratives </h1>
  <p>N° sécurité sociale : 1 38 05 12 345 678 90</p>
  <p>N° carte vitale : 1 38 05 12 345 678 90</p>
  <p>N° carte mutuelle : 1 38 05 12 345 678 90</p>
  <p>N° carte groupe sanguin : 1 38 05 12 345 678 90</p>

  <h1 class ="mt-2">A savoir sur moi </h1>
  <p>Donneur d'organe : Oui</p>
  <p>Fumeur : non</p>
  <p>Contact ICE : </p>
  <p> - M.BALDIN (pére) : 06 12 34 56 78</p>
  <p> - Mme.BALDIN (mère) : 06 98 76 54 32</p>

</div>

<%= link_to(pathologies_path) do %>
  <p class= "m-1 bouton d-flex justify-content-center">Pathologies</p>
<% end %>

<%= link_to(historical_path) do %>
  <p class= "m-1 bouton d-flex justify-content-center">Historique</p>
<% end %>
<p class ="mt-2 justify-content-center"> . </p>