config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "pages#home"
  get "historical", to: "pages#historical"
  get "profil", to: "pages#profil"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :prescriptions do
    resources :follow_ups, only: %i[index show new create edit update]
    resources :measures, only: %i[show new create] do
      resources :measurements, only: %i[new create edit update]
    end
  end
  resources :follow_ups, only: %i[edit update destroy]
  resources :measures, only: %i[index show edit update destroy]

  resources :pathologies, only: %i[index show edit update new create]
  resources :appointments
  get "day_calendar/:date_str", to: "appointments#day_calendar", as: :day_calendar
  # get "dashboard", to: "pages#dashboard"
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user

  validates :appointment_date, presence: true
  validates :title, presence: true

  def start_time
  self.appointment_date
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :calendar_models, only: [:index]

  def day_calendar
    @searched_date = Date.parse(params[:date_str])
    calendar_models(@searched_date)
  end

  def index; end

  def show
    @appointment = Appointment.find(params[:id])
  end

  def new
    @appointment = Appointment.new
  end

  def create
    @user = current_user
    @appointment = Appointment.new(appointment_params)
    @appointment.user = @user
      if @appointment.save!
        redirect_to appointments_path
      else
      render :new, status: :unprocessable_entity
      end
  end

  def edit
    @appointment = Appointment.find(params[:id])
  end

  def update
    @appointment = Appointment.find(params[:id])
    @appointment.update(appointment_params)
    redirect_to appointmentt_path(@appointment)
  end

    private

  def appointment_params
    params.require(:appointment).permit(:title, :appointment_date, :appointment_time, :address, :user_id)
  end

  def calendar_models(searched_date = Date.today)
      # start_date = params.fetch(:start_date, Date.today).to_date
      # end_date = params.fetch(:start_date, Date.today).to_date
        # # PRESCRIPTIONS
      @prescriptions = Prescription.where(user: current_user, end_date: searched_date.beginning_of_month.beginning_of_week..searched_date.end_of_month.end_of_week)

        # # FOLLOw-UPS
      prescriptions_user = Prescription.where(user_id: current_user)
      follow_ups = prescriptions_user.flat_map { |prescription| prescription.follow_ups }
      @follow_ups = FollowUp.where(id: follow_ups.pluck(:id))
      @follow_ups = @follow_ups.map(&:fus_for_calendar).flatten
      # @follow_ups.where(start_date: start_date.beginning_of_month.beginning_of_week..start_date.end_of_month.end_of_week)
      # raise
      # Generate bullets for calendar

        # # MEASURES
      measures = prescriptions_user.flat_map { |prescription| prescription.measures }
      @measures = Measure.where(id: measures.pluck(:id))
      @measures = @measures.map(&:measure_for_calendar).flatten

      # @measures.where(start_date: start_date.beginning_of_month.beginning_of_week..start_date.end_of_month.end_of_week)

      # # APPOINTMENT
      @appointments = Appointment.where(user: current_user, appointment_date: searched_date.beginning_of_month.beginning_of_week..searched_date.end_of_month.end_of_week)
  end

end

app/views/appointments/day_calendar.html.erb
  <div class="header">
    <div class= "header-title">
      <h1>Calendrier journalier</h1>
    </div>
  </div>

<div class="container">
   <div class="daily_calendar_header">
      <%= calendar(start_date: @searched_date, number_of_days: 1, events: @prescriptions + @follow_ups + @measures + @appointments) do |date, events| %>
        <%= date %>
        <div class="daily_calendar_header">
          <% events.each do |event| %>

            <% if event.is_a?(Prescription) %>
                  <%= link_to prescription_path(event) do %>
                            <div class="prescription-daily-calendar">
                              <p class="bullet-daily-prescription">⚕️</p>
                                          <div class="text-daily-calendar">
                                            <%= event.end_date%>
                                          </div>
                            </div>
                  <% end %>
               <br>

            <% elsif event.is_a?(FollowUp) %>
              <%= link_to prescription_follow_up_path(event.prescription, event) do %>
                  <div class="follow-up-daily-calendar">
                      <p class="bullet-daily-follow-up">💊</p>
                      <div class="text-daily-calendar">
                          <%= event.title %>
                          <br>
                          <%= event.description %>
                    <%# <p class="daily-hourly-frequency"><%= event.hourly_frequency %>
                      </div>
                    </div>
              <% end %>

            <% elsif event.is_a?(Measure) %>
              <%= link_to measure_path(event) do %>
                    <div class="measure-daily-calendar">
                        <p class="bullet-daily-measures">📈</p>
                      <div class="text-daily-calendar">
                        <%= event.title %>
                        <br>
                        <%= event.description%>
                        <%# <p class="daily-hourly-frequency"><%= event.hourly_frequency %>
                      </div>
                    </div>
              <% end %>


          <% elsif event.is_a?(Appointment) %>
            <%= link_to appointment_path(event) do %>
                  <div class="appointment-daily-calendar">
                     <p class="bullet-daily-appointment" >🛎️</p>
                     <div class="text-daily-calendar">
                        <%= event.title %>
                        <br>
                        <%# <%= event.description%>
                    </div>
                  </div>
            <% end %>


          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/appointments/draft.html.erb
<div class="header">
  <div class= "header-title">
  <h1>Calendrier</h1>
  </div>
</div>

<div class="container">
  <div class="calendar-container">
    <%= month_calendar(events: @prescriptions + @follow_ups + @measures + @appointments) do |date, events| %>
      <%= link_to day_calendar_path(date), class: "day-link" do %>
        <%= date %>
      <% end %>
      <div class="emojis">
        <% events.each do |event| %>
          <% if event.is_a?(Prescription) %>
            <%= link_to prescription_path(event) do %>
                <p class="emoji">📝</p>
            <% end %>
          <% elsif event.is_a?(FollowUp) %>
            <%= link_to prescription_follow_up_path(event.prescription, event) do %>
                <%# <%= event.title.first %>
                <p class="emoji">💊</p>
                <%# <p class="hourly-frequency"> %>
                <%# <%= event.hourly_frequency %>
            <% end %>
          <% elsif event.is_a?(Measure) %>
            <%= link_to measure_path(event) do %>
                <%# <%= event.title %>
                <%# <%= event.hourly_frequency %>
                <p class="emoji">📈</p>
            <% end %>
          <% elsif event.is_a?(Appointment) %>
            <%= link_to appointment_path(event) do %>
                <%# <%= event.title %>
                <p class="emoji">🛎️</p>
            <% end %>
          <% end %>
        <% end %>
      </div>
    <% end %>
    <div class="legend-container">
      <p class="legend-title">Légende</p>
      <div class="colored-legend">
        <div class="left-side-legend">
          <div class="bullet-prescription">
            <div class = "prescription-calendar"></div>
            <p> Prescription</p>
          </div>

          <div class="bullet-follow-up">
            <div class = "follow-up-calendar"></div>
            <p> Traitement</p>
          </div>
        </div>
        <div class="right-side-legend">

          <div class="bullet-measures">
            <div class = "measure-calendar"></div>
            <p> Auto-relevé</p>
          </div>

          <div class="bullet-appointment">
            <div class = "appointment-calendar"></div>
            <p> Rendez-vous</p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <p class= "calendar-button-container">
    <%= link_to "Ajouter un rdv", new_appointment_path, class: "bouton" %>
  </p>
  <%# <p><%= link_to "Modifier un rdv", edit_appointment_path, class: "bouton"%>
</div>

<p class = "mt-3 justify-content-center">.</p>



<%# //////// day_calendar_ %>



<div class="header">
  <div class= "header-title">
    <h1>Calendrier <br>Journalier</h1>
  </div>
</div>

<div class = "container">
  <div class = "daily_calendar_header">
    <%= calendar(number_of_days: 1, events: @prescriptions + @follow_ups + @measures + @appointments) do |date, events| %>
    <%= date %>
      <div class = "daily_calendar_header">
      <% events.each do |event| %>
        <% if event.is_a?(Prescription) %>
      <%= link_to prescription_path(event) do %>
          <div class="prescription-daily-calendar">
              <p class = "bullet-daily-prescription"></p>
              <div class="text-daily-calendar">
                <%= event.end_date%>
              </div>
          </div>
        <% end %>
        <br>

        <% elsif event.is_a?(FollowUp) %>
            <%= link_to prescription_follow_up_path(event.prescription, event) do %>
              <div class="follow-up-daily-calendar">
              <p class = "bullet-daily-follow-up"></p>
                  <div class="text-daily-calendar">
                   <%= event.title %>
                   <br>
                  <%= event.description %>
                  <%# <p class="daily-hourly-frequency"><%= event.hourly_frequency %>
                  </div>
              </div>
            <% end %>
            <br>

        <% elsif event.is_a?(Measure) %>
            <%= link_to measure_path(event) do %>
              <div class="measure-daily-calendar">
                <p class = "bullet-daily-measures"></p>
                <div class="text-daily-calendar">
                <%= event.title %>
                <br>
                <%= event.description%>
                <%# <p class="daily-hourly-frequency"><%= event.hourly_frequency %>
                </div>
              </div>

            <% end %>
            <br>

          <% elsif event.is_a?(Appointment) %>
            <%= link_to appointment_path(event) do %>
              <div class="appointment-daily-calendar">
              <p class = "bullet-daily-appointment" ></p>
                <div class="text-daily-calendar">
                <%= event.title %>
                <br>
                <%= event.description%>
                </div>
              </div>
          <% end %>
          <br>
        <% end %>
      <% end %>
    <% end %>
    </div>



 </div>
</div>

app/views/appointments/edit.html.erb
<div class="header">
  <div class= "header-title">
    <h1>Modifier vos pathologies</h1>
  </div>
</div>
<div class="background">
  <div class="bg-white rounded p-3 shadow">
    <h1 class="edit-form">Modifier vos pathologies</h1>
      <div class="form">
      <%= simple_form_for @appointment do |f| %>
      <div>
      <%= f.input :titre, placeholder: 'Titre du rendez-vous'%>
      <%= f.input :date, placeholder: 'date' %>
      </div>
        <%= f.submit 'edit',class: "bouton edit-style", value: "Modifier le rdv" %>
      <% end %>
      </div>
  </div>
</div>

app/views/appointments/index.html.erb
<div class="header">
  <div class= "header-title">
  <h1>Calendrier</h1>
  </div>
</div>

<div class="container">
  <div class="calendar-container">
    <%= month_calendar(events: @prescriptions + @follow_ups + @measures + @appointments) do |date, events| %>
      <%= link_to day_calendar_path(date.to_s), class: "day-link" do %>
        <%= date.day %>
      <% end %>
      <div class="emojis">
        <% @prescriptions = events.select { |event| event.is_a?(Prescription) } %>
        <% @follow_ups = events.select { |event| event.is_a?(FollowUp) } %>
        <% @measures = events.select { |event| event.is_a?(Measure) } %>
        <% @appointments = events.select { |event| event.is_a?(Appointment) } %>

        <div class="aligned-emojis">
          <% @prescriptions.each do |prescription| %>
            <%= link_to prescription_path(prescription) do %>
              <p class="emoji-presc">⚕️</p>
            <% end %>
          <% end %>
        </div>

        <div class="aligned-emojis">
          <% @follow_ups.each do |follow_up| %>
            <%= link_to follow_up_path(follow_up) do %>
              <p class="emoji">💊</p>
            <% end %>
          <% end %>
        </div>

        <div class="aligned-emojis">
          <% @measures.each do |measure| %>
            <%= link_to measure_path(measure) do %>
              <p class="emoji">📈</p>
            <% end %>
          <% end %>
        </div>

        <div class="aligned-emojis">
          <% @appointments.each do |appointment| %>
            <%= link_to appointment_path(appointment) do %>
              <p class="emoji">🛎️</p>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
    <div class="legend-container">
      <p class="legend-title">Légende</p>
      <div class="colored-legend">
        <div class="left-side-legend">
          <div class="bullet-prescription">
            <div class = "prescription-calendar">⚕️</div>
            <p> Prescription</p>
          </div>

          <div class="bullet-follow-up">
            <div class = "follow-up-calendar">💊</div>
            <p> Traitement</p>
          </div>
        </div>
        <div class="right-side-legend">

          <div class="bullet-measures">
            <div class = "measure-calendar">📈</div>
            <p> Auto-relevé</p>
          </div>

          <div class="bullet-appointment">
            <div class = "appointment-calendar">🛎️</div>
            <p> Rendez-vous</p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <p class= "calendar-button-container">
    <%= link_to "Ajouter un rdv", new_appointment_path, class: "bouton" %>
  </p>
  <%# <p><%= link_to "Modifier un rdv", edit_appointment_path, class: "bouton"%>
</div>

<p class = "mt-3 justify-content-center">.</p>

app/views/appointments/new.html.erb
<div class="header">
  <div class= "header-title">
    <h1>Créer un RDV</h1>
  </div>
</div>
<div class="calendar">
<div class="background">
  <div class="bg-white rounded p-3 shadow">

    <%= simple_form_for @appointment do |f| %>
      <div>
      <%= f.input :title,  label: "Titre", placeholder: 'Titre', class: "black-label" %>
      </div>

      <div>
        <%= f.input :appointment_date, label: "Date", as: :date, html5: true %>
      </div>

       <div>
        <%= f.input :appointment_time, label: "Heure", as: :time %>
      </div>

       <div>
        <%= f.input :address, label: "Adresse", placeholder: 'Adresse'  %>
      </div>

       <div>
        <%= f.input :practician, label: "Practicien", placeholder: "Practicien "%>
      </div>


      <%= f.submit class: "bouton edit-style", value: "Créer" %>

    <% end %>
  </div>
</div>
</div>

app/views/appointments/show.html.erb
<div class = container>
  <h1>Votre Rendez-vous</h1>
    <ul class = "measures">
  <h2 class = "measure-title"><%= @appointment.title %></h1>
      <div class = "measure-description">
        <p><%= @appointment.appointment_date %></p>
        <p><%= @appointment.appointment_time %></p>
        <p><%= @appointment.address %></p>
      </div>
    </ul>
</div>